#!/bin/sh
# Compile:by-lanse    2018-08-27
echo
echo -e "\e[1;36m 下载 Fq 翻网规则 \e[0m"
TMP_FQ=/tmp/tmp_fq
FQ=/tmp/fq
[ -f ${FQ} ] && rm -rf ${FQ}
for URL in \
	"https://raw.githubusercontent.com/sy618/hosts/master/dnsmasq/dnsfq" \
	"https://raw.githubusercontent.com/vokins/yhosts/master/dnsmasq/union.conf" \
	"https://c.nnjsx.cn/GL/dnsmasq/update/adblock/easylistchina.txt" \
	"https://raw.githubusercontent.com/vokins/yhosts/master/dnsmasq/ip.conf"
do
	wget --no-check-certificate -t 15 -T 50 -O- "${URL}" \
	| sed -e "s/#.*$//" -e "/# /d" -e "/\#a/d" -e "/^$/d" -e "/\#s/d" -e "/#★/d" >> ${FQ}
done
sleep 3
echo -e "\033[45;37m 翻网规则下载完成 \033[0m"
echo
#rm ${TMP_FQ} 2> /dev/null
