#!/bin/sh
# Compile:by-lanse  2017-08-24
LOGTIME=$(date "+%m-%d %H:%M:%S")
echo
echo " 检测脚本版本."
if [ ! -f /tmp/hsfq_script_up.sh ]; then
	wget --no-check-certificate https://raw.githubusercontent.com/896660689/Hsfq/master/hsfq_script.sh -O /tmp/hsfq_script_up.sh;chmod 775 /tmp/hsfq_script_up.sh
	echo
	cat /tmp/hsfq_script_up.sh /etc/storage/dnsmasq.d/hsfq_script.sh | awk '{ print$0}' | sort | uniq -u > /tmp/hsfq_script_up.txt && sleep 2
	if [ ! -s "/tmp/hsfq_script_up.txt" ]; then
		echo -e "\e[1;33m HSFQ 安装脚本已为最新,无需更新.\e[0m" && rm -f /tmp/hsfq_script_up.sh && rm -f /tmp/hsfq_script_up.txt
	else
		cp -f /tmp/hsfq_script_up.sh /etc/storage/dnsmasq.d/hsfq_script.sh
		mv -f /tmp/hsfq_script_up.sh /tmp/hsfq_script.sh && rm -f /tmp/hsfq_script_up.txt
		echo -e "\033[41;37m新版脚本更新完成.须重新安装程序\033[0m"
		echo
		sleep 5
		echo
		sh /tmp/hsfq_install
	fi
fi
if [ -x "/etc/storage/dnsmasq.d/hsfq_update.sh" ]; then
	logger -t "【$LOGTIME】" " 开始运行翻墙去广告更新任务..."
	[ -f /tmp/tmp_fq_up ] && rm -f /tmp/tmp_fq_up
	[ -f /tmp/tmp_hs_up ] && rm -f /tmp/tmp_hs_up
	sleep 2
	# 准备翻墙 FQ 文件
	wget --no-check-certificate -t 10 -T 30 https://raw.githubusercontent.com/896660689/Hsfq/master/tmp_fq_up -qO \
	/tmp/tmp_fq_up && chmod 755 /tmp/tmp_fq_up && . /tmp/tmp_fq_up
	sleep 2
fi
if [ -x "/etc/storage/dnsmasq.d/hsfq_update.sh" ]; then
	# 准备去广告 HOSTS 文件
	wget --no-check-certificate -t 10 -T 30 https://raw.githubusercontent.com/896660689/Hsfq/master/tmp_hs_up -qO \
	/tmp/tmp_hs_up && chmod 755 /tmp/tmp_hs_up && . /tmp/tmp_hs_up
	restart_dhcpd && /usr/sbin/dnsmasq restart 2>&1 >/dev/null
	sleep 3
	rm -rf /tmp/tmp_fq_up /tmp/tmp_hs_up
fi	
echo

