#!/bin/sh
# by lanse
## 配置dnsmasq.conf启动规则
grep "storage" /etc/storage/dnsmasq/dnsmasq.conf
if [ $? -eq 0 ]; then
	sed -i '/127.0.0.1/d' /etc/storage/dnsmasq/dnsmasq.conf
	sed -i '/log/d' /etc/storage/dnsmasq/dnsmasq.conf
	sed -i '/no-hosts/d' /etc/storage/dnsmasq/dnsmasq.conf
	sed -i '/strict-order/d' /etc/storage/dnsmasq/dnsmasq.conf
	sed -i '/1800/d' /etc/storage/dnsmasq/dnsmasq.conf	
	sed -i '/dnsmasq.d/d' /etc/storage/dnsmasq/dnsmasq.conf
else
	echo "开始写入启动代码"
fi
route_vlan=`/sbin/ifconfig br0 |grep "inet addr"| cut -f 2 -d ":"|cut -f 1 -d " " `
Conf=/etc/storage/dnsmasq/dnsmasq.conf
echo "listen-address=${route_vlan},127.0.0.1
# 添加监听地址
# 开启日志选项
log-queries
log-facility=/tmp/dnsmasq.log
# 异步log,缓解阻塞，提高性能。默认为5，最大为100
log-async=50
# DNS服务器严格按顺序使用
strict-order
# 缓存最长时间
min-cache-ttl=1800
# 指定服务器'域名''地址'文件夹
conf-dir=/etc/storage/dnsmasq.d/conf
# 关闭内置hosts，配合启用第三方hosts
no-hosts
# 指定hosts解析'地址''域名'文件夹
addn-hosts=/etc/storage/dnsmasq.d/hosts" sed -e "/# /d" >> ${Conf}
echo
sleep 2
rm /tmp/tmp_dnsmasq >/dev/null 2>&1
