#!/bin/sh
# by lanse
LOGTIME=$(date "+%m-%d %H:%M:%S")
route_vlan=`/sbin/ifconfig br0 |grep "inet addr"| cut -f 2 -d ":"|cut -f 1 -d " " `
username=`nvram get http_username`
echo -e "\e[1;36m FQ 翻墙规则开始下载... \e[0m"

# 下载 FQ 组合规则
wget --no-check-certificate https://raw.githubusercontent.com/896660689/Hsfq/master/hsfq -qO \
/tmp/fq.conf && sleep 2 && chmod +x /tmp/fq.conf && . /tmp/fq.conf
echo
# 添加用户自定规则缓存
cp /etc/storage/dnsmasq.d/userlist /tmp/userlist

# 合并 dnsmasq 缓存
cat /tmp/userlist /tmp/fq > /tmp/hosts_fq

sleep 2
# 删除 dnsmasq 缓存
rm -rf /tmp/userlist
rm -rf /tmp/fq
rm -rf /tmp/fq.conf

# 删除注释
sed -i '/# /d' /tmp/hosts_fq

# 创建 dnsmasq 规则文件
cat > /tmp/hosts_fq.conf <<EOF
##########################################################
## 域名自定义 dnsmasq 设置	【2017 by.lanse】	##
##########################################################
address=/localhost/127.0.0.1
address=/localhost/::1
address=/ip6-localhost/::1
address=/ip6-loopback/::1
# 以下示例.去“#”生效
#address=/mit.ru/izmuroma.ru/10.25.11.30
EOF

# 去重排序规则
sort -n /tmp/hosts_fq | uniq | sed -E -e "/^$/d" -e "s/[[:space:]][[:space:]]*/ /g" >> /tmp/hosts_fq.conf
sleep 2
# 修饰结束
sed -i '$a # Modified DNS end' /tmp/hosts_fq.conf

echo " 更新 hosts_fq 规则."
echo
if [ -f /tmp/hosts_fq.conf ]; then
	echo | awk '{print$0}' /tmp/hosts_fq.conf /etc/storage/dnsmasq.d/conf/hosts_fq.conf | sort | uniq -u > /tmp/hosts_fq.txt && sleep 2
	if [ ! -s "/tmp/hosts_fq.txt" ]; then
		logger -t "【$LOGTIME】" "FQ 规则已为最新,无需更新..."
		echo
		echo -e "\e[1;33m FQ 已为最新规则无需更新.\e[0m" && rm -rf /tmp/hosts_fq.conf
	else
		logger -t "【$LOGTIME】" "$LOGTIME FQ 规则更新完成..."
		echo
		mv -f /tmp/hosts_fq.conf /etc/storage/dnsmasq.d/conf/hosts_fq.conf && sleep 3
		if [ $0 == 0 ]; then
			echo -e "\e[1;33m FQ 规则更新完成.\e[0m"
		else
			logger -t "【$LOGTIME】" "FQ 更新失败，重新启动更新任务..."
			echo
			echo -e "\033[41;37m FQ 更新失败，重新启动更新任务\033[0m"
			sh /tmp/tmp_fq_up
		fi	
	fi	
fi

# 删除临时合并缓存
rm -f /tmp/hosts_fq.txt
rm -rf /tmp/hosts_fq
exit
